package net.deepthought.controller.enums;

/**
 * Created by ganymed on 25/12/14.
 */
public enum FieldWithUnsavedChanges {

  EntryTitle,
  EntryAbstract,
  EntryContent,
  EntrySeriesTitle,
  EntryReference,
  EntryReferenceIndication,
  EntryReferenceIndicationStartUnit,
  EntryReferenceIndicationEnd,
  EntryReferenceIndicationEndUnit,
  EntryReferenceSubDivision,
  EntryPersons,
  EntryTags,
  EntryCategories,
  EntryParentEntry,
  EntrySubEntries,
  EntryLanguage,
  EntryNotes,
  EntryLinkGroups,
  EntryFiles,
  EntryPreviewImage,
  EntryEvaluation,
  EntryRating,

  TagName,
  TagDescription,

  CategoryName,
  CategoryDescription,

  PersonFirstName,
  PersonMiddleNames,
  PersonLastName,
  PersonTitle,
  PersonPrefix,
  PersonSuffix,
  PersonAbbreviation,
  PersonGender,
  PersonNotes,

  FileFileLocation,
  FileIsFolder,
  FileFolderLocation,
  FileName,
  FileNotes,
  FileImageWidth,
  FileImageHeight,
  FileImageAlsoAttachToEntity,

  ReferenceTitle,
  ReferenceSubTitle,
  ReferenceAbstract,
  ReferencePersons,
  ReferenceOnlineAddress,
  ReferenceLastAccess,
  ReferenceNotes,
  ReferenceBaseFiles,


  SeriesTitleTitle,
  SeriesTitleSubTitle,
  SeriesTitleAbstract,
  SeriesTitlePersons,
  SeriesTitleOnlineAddress,
  SeriesTitleLastAccess,
  SeriesTitleNotes,
  SeriesTitleFiles,
  SeriesTitleSeriesTitleCategory,
  SeriesTitleTitleSupplement,
  SeriesTitleTableOfContents,
  SeriesTitlePublisher,
  SeriesTitleFirstDayOfPublication,
  SeriesTitleLastDayOfPublication,
  SeriesTitleStandardAbbreviation,
  SeriesTitleUserAbbreviation1,
  SeriesTitleUserAbbreviation2,
  SeriesTitleSerialParts,

  ReferenceSeriesTitle,
  ReferenceReferenceCategory,
  ReferenceTitleSupplement,
  ReferenceTableOfContents,
  ReferenceEdition,
  ReferenceVolume,
  ReferenceIssueOrPublishingDate,
  ReferencePlaceOfPublication,
  ReferencePublisher,
  ReferenceIsbnOrIssn,
  ReferenceReferenceLength,
  ReferenceReferenceLengthUnit,
  ReferenceIssue,
  ReferenceYear,
  ReferenceDoi,
  ReferencePrice,
  ReferenceLanguage,
  ReferenceSubDivisions,

  ReferenceSubDivisionTitle,
  ReferenceSubDivisionSubTitle,
  ReferenceSubDivisionAbstract,
  ReferenceSubDivisionPersons,
  ReferenceSubDivisionOnlineAddress,
  ReferenceSubDivisionLastAccess,
  ReferenceSubDivisionNotes,
  ReferenceSubDivisionFiles,

}
