package net.deepthought.controller.enums;

/**
 * Created by ganymed on 25/12/14.
 */
public enum FieldWithUnsavedChanges {

  EntryTitle,
  EntrySubTitle,
  EntryTemplate,
  EntryAbstract,
  EntryContent,
  EntryContentFormat,
  EntrySeriesTitle,
  EntryReference,
  EntryReferenceStart,
  EntryReferenceStartUnit,
  EntryReferenceEnd,
  EntryReferenceEndUnit,
  EntryReferenceSubDivision,
  EntryPersons,
  EntryTags,
  EntryCategories,
  EntryParentEntry,
  EntrySubEntries,
  EntryLanguage,
  EntryNotes,
  EntryLinkGroups,
  EntryFiles,
  EntryPreviewImage,
  EntryEvaluation,
  EntryRating,

  PersonFirstName,
  PersonMiddleNames,
  PersonLastName,
  PersonTitle,
  PersonPrefix,
  PersonSuffix,
  PersonAbbreviation,
  PersonGender,
  PersonNotes,

  FileFileLocation,
  FileIsFolder,
  FileFolderLocation,
  FileName,
  FileNotes,

  ReferenceBaseTitle,
  ReferenceBaseSubTitle,
  ReferenceBaseAbstract,
  ReferenceBaseOnlineAddress,
  ReferenceBaseLastAccess,
  ReferenceBaseNotes,
  ReferenceBaseFiles,

  ReferenceSeriesTitle,
  ReferenceReferenceCategory,
  ReferenceTitleSupplement,
  ReferenceTableOfContents,
  ReferencePersons,
  ReferenceEdition,
  ReferenceVolume,
  ReferencePublishingDate,
  ReferencePlaceOfPublication,
  ReferencePublisher,
  ReferenceIsbnOrIssn,
  ReferenceReferenceLength,
  ReferenceReferenceLengthUnit,
  ReferenceIssue,
  ReferenceYear,
  ReferenceDoi,
  ReferencePrice,
  ReferenceLanguage,
  ReferenceSubDivisions,

  SeriesTitleSeriesTitleCategory,
  SeriesTitleTitleSupplement,
  SeriesTitleTableOfContents,
  SeriesTitlePublisher,
  SeriesTitleFirstDayOfPublication,
  SeriesTitleLastDayOfPublication,
  SeriesTitleStandardAbbreviation,
  SeriesTitleUserAbbreviation1,
  SeriesTitleUserAbbreviation2,
  SeriesTitleSerialParts,

}
